lanuage: python

python:
  - '3.7'

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
    - os: osx
      # osx_image: xcode10.2
      sudo: true

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8

before_install:
  - travis/install-conda.sh
  - echo "which pip after export"
  - which pip
  - which python
  - which conda
  - hash -r
  - travis/install-pip.sh

install:
  - python setup.py build
  - python setup.py install

before_script:
  - flake8 --exit-zero .

script:
  - python setup.py test
  - pytest --cov=hubness

after_success:
  - codecov

cache:
  - pip
  - ccache
  - packages
  - directories:
      - "$HOME/.cache/pip"
      - "$HOME/virtualenv"
      - "$HOME/miniconda"

branches:
  only:
  - master
  - develop
